# fly.toml app configuration file generated for test-13-e5685d51-607b-4429-af94-b76049b2d552-server on 2024-06-18T20:33:32+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'test-13-e5685d51-607b-4429-af94-b76049b2d552-server'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
